// parser/__tests__/region-pairing.test.mjs
// Unit tests for parser/dwg/dxf-loader.js and parser/dwg/region-pairing.js.
// Uses fixtures from parser/__tests__/fixtures/ generated by tools/build-siriu-test-fixture.mjs.
// Run: node parser/__tests__/region-pairing.test.mjs

import "fake-indexeddb/auto";
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { URL } from "node:url";

const subset = JSON.parse(
  readFileSync(new URL("./fixtures/siriu-subset.json", import.meta.url), "utf8"),
);
const gt = JSON.parse(
  readFileSync(new URL("./fixtures/siriu-ground-truth.json", import.meta.url), "utf8"),
);

import {
  buildAdjacencyGraph,
  buildPostIndex,
  DEFAULT_TOLERANCE_M,
  pairPostsAgainstRegion,
} from "../dwg/region-pairing.js";
import { latLonToUtm, haversineMeters } from "../geo/utm-calibrator.js";

test("R-DWG-01: subset posts are in Siriu UTM range", () => {
  assert.ok(Array.isArray(subset.posts));
  assert.ok(subset.posts.length >= 20);

  for (const p of subset.posts) {
    assert.equal(typeof p.x, "number");
    assert.equal(typeof p.y, "number");
    assert.ok(p.x >= 729000 && p.x <= 736000, `bad easting ${p.x}`);
    assert.ok(p.y >= 6900000 && p.y <= 6906000, `bad northing ${p.y}`);
  }
});

test("R-DWG-02: subset post blocks look like pod_*", () => {
  let hasPod = false;
  let hasCommon = false;

  for (const p of subset.posts) {
    assert.equal(typeof p.block, "string");
    if (/^pod_/.test(p.block)) hasPod = true;
    if (p.block === "pod_con_dtt") hasCommon = true;
  }

  assert.ok(hasPod, "expected at least one pod_* block");
  assert.ok(hasCommon, "expected at least one pod_con_dtt block");
});

test("R-DWG-03: cable endpoints snap near posts (>=85% within 3m)", () => {
  assert.ok(Array.isArray(subset.cableEdges));
  assert.ok(subset.cableEdges.length >= 10);

  const endpoints = [];
  for (const e of subset.cableEdges) {
    endpoints.push(e.a, e.b);
  }

  let within = 0;
  for (const pt of endpoints) {
    let best = Infinity;
    for (const p of subset.posts) {
      const d = Math.hypot(p.x - pt.x, p.y - pt.y);
      if (d < best) best = d;
    }
    if (best <= 3) within++;
  }

  const ratio = within / endpoints.length;
  // Note: the full `siriu.dxf` has p90 ~2.07m, but this committed subset is bbox-filtered.
  // We keep the assertion strong enough to catch gross extraction errors while matching the subset.
  assert.ok(ratio >= 0.85, `snap ratio too low: ${(ratio * 100).toFixed(1)}%`);
});

test("buildPostIndex-01: nearest INSERT to post-01 GPS is within 5m", () => {
  const postIndex = buildPostIndex(subset.posts);
  const post01 = gt.find((p) => p.number === 1);
  assert.ok(post01);

  const { easting, northing } = latLonToUtm(post01.lat, post01.lon);
  const found = postIndex.search({
    minX: easting - 10,
    minY: northing - 10,
    maxX: easting + 10,
    maxY: northing + 10,
  });
  assert.ok(found.length >= 1);

  let best = Infinity;
  for (const p of found) {
    best = Math.min(best, Math.hypot(p.x - easting, p.y - northing));
  }
  assert.ok(best < 5, `best distance ${best.toFixed(2)}m`);
});

test("buildAdjacencyGraph-01: anchor post has at least one neighbour", () => {
  const postIndex = buildPostIndex(subset.posts);
  const adjacencyGraph = buildAdjacencyGraph(subset.posts, subset.cableEdges);
  const post01 = gt.find((p) => p.number === 1);
  assert.ok(post01);

  const { easting, northing } = latLonToUtm(post01.lat, post01.lon);
  const found = postIndex.search({
    minX: easting - 10,
    minY: northing - 10,
    maxX: easting + 10,
    maxY: northing + 10,
  });
  assert.ok(found.length >= 1);

  let bestIdx = -1;
  let best = Infinity;
  for (let i = 0; i < subset.posts.length; i++) {
    const p = subset.posts[i];
    const d = Math.hypot(p.x - easting, p.y - northing);
    if (d < best) {
      best = d;
      bestIdx = i;
    }
  }
  assert.ok(bestIdx >= 0);

  const neigh = adjacencyGraph.get(bestIdx);
  assert.ok(neigh instanceof Set);
  assert.ok(neigh.size >= 1);
});

test("pairPostsAgainstRegion-anchor-01: 1-post route succeeds within 5m", () => {
  const post01 = gt.find((p) => p.number === 1);
  assert.ok(post01);

  const fakePosts = [{ number: 1, x: 0, y: 0, pageNum: 1 }];
  const warnings = [];

  const postIndex = buildPostIndex(subset.posts);
  const adjacencyGraph = buildAdjacencyGraph(subset.posts, subset.cableEdges);

  const res = pairPostsAgainstRegion({
    posts: fakePosts,
    distances: [],
    connections: [],
    startLat: post01.lat,
    startLon: post01.lon,
    region: { posts: subset.posts, cableEdges: subset.cableEdges, crs: { zone: 22 } },
    postIndex,
    adjacencyGraph,
    warnings,
  });

  assert.equal(res.ok, true);
  assert.equal(res.coords.length, 1);
  assert.equal(res.coords[0].postNumber, 1);
  const err = haversineMeters(res.coords[0].lat, res.coords[0].lon, post01.lat, post01.lon);
  assert.ok(err < 5, `err=${err.toFixed(2)}m`);
});

test("pairPostsAgainstRegion-failure-01: anchor fails when > tolerance away", () => {
  const post01 = gt.find((p) => p.number === 1);
  assert.ok(post01);

  const postIndex = buildPostIndex(subset.posts);
  const adjacencyGraph = buildAdjacencyGraph(subset.posts, subset.cableEdges);
  const warnings = [];

  const farLat = post01.lat + 0.00018; // ~20m north
  const res = pairPostsAgainstRegion({
    posts: [{ number: 1, x: 0, y: 0, pageNum: 1 }],
    distances: [],
    connections: [],
    startLat: farLat,
    startLon: post01.lon,
    region: { posts: subset.posts, cableEdges: subset.cableEdges, crs: { zone: 22 } },
    postIndex,
    adjacencyGraph,
    warnings,
  });

  assert.equal(res.ok, false);
  assert.equal(res.failedAt, 1);
  assert.ok(warnings.some((w) => w.kind === "dwg-pair-fail"));
  assert.equal(DEFAULT_TOLERANCE_M, 15);
});

test("pairPostsAgainstRegion-collision-01: detects duplicate INSERT claim", () => {
  const post01 = gt.find((p) => p.number === 1);
  assert.ok(post01);

  const fakePosts = [
    { number: 1, x: 0, y: 0, pageNum: 1 },
    { number: 2, x: 0, y: 10, pageNum: 1 }, // bearing north, tiny distance → likely same candidate
  ];
  const warnings = [];

  const postIndex = buildPostIndex(subset.posts);
  const adjacencyGraph = buildAdjacencyGraph(subset.posts, subset.cableEdges);

  const res = pairPostsAgainstRegion({
    posts: fakePosts,
    distances: [{ from: 1, to: 2, meters: 0.1 }],
    connections: [{ from: 1, to: 2, gap: false }],
    startLat: post01.lat,
    startLon: post01.lon,
    region: { posts: subset.posts, cableEdges: subset.cableEdges, crs: { zone: 22 } },
    postIndex,
    adjacencyGraph,
    warnings,
  });

  assert.equal(res.ok, false);
  assert.ok(warnings.some((w) => w.kind === "dwg-pair-collision"));
});

test("pairPostsAgainstRegion-2post-01: simple 2-post walk succeeds near ground truth", () => {
  const p1 = gt.find((p) => p.number === 1);
  const p2 = gt.find((p) => p.number === 2);
  assert.ok(p1 && p2);

  const d = haversineMeters(p1.lat, p1.lon, p2.lat, p2.lon);
  const { easting: e1, northing: n1 } = latLonToUtm(p1.lat, p1.lon);
  const { easting: e2, northing: n2 } = latLonToUtm(p2.lat, p2.lon);
  const bRad = Math.atan2(e2 - e1, n2 - n1);

  const fakePosts = [
    { number: 1, x: 0, y: 0, pageNum: 1 },
    { number: 2, x: Math.sin(bRad) * 10, y: Math.cos(bRad) * 10, pageNum: 1 },
  ];

  const postIndex = buildPostIndex(subset.posts);
  const adjacencyGraph = buildAdjacencyGraph(subset.posts, subset.cableEdges);
  const warnings = [];

  const res = pairPostsAgainstRegion({
    posts: fakePosts,
    distances: [{ from: 1, to: 2, meters: d }],
    connections: [{ from: 1, to: 2, gap: false }],
    startLat: p1.lat,
    startLon: p1.lon,
    region: { posts: subset.posts, cableEdges: subset.cableEdges, crs: { zone: 22 } },
    postIndex,
    adjacencyGraph,
    warnings,
  });

  assert.equal(res.ok, true);
  const c1 = res.coords.find((c) => c.postNumber === 1);
  const c2 = res.coords.find((c) => c.postNumber === 2);
  assert.ok(c1 && c2);

  const e1m = haversineMeters(c1.lat, c1.lon, p1.lat, p1.lon);
  const e2m = haversineMeters(c2.lat, c2.lon, p2.lat, p2.lon);
  assert.ok(e1m < 8, `post1 err=${e1m.toFixed(2)}m`);
  assert.ok(e2m < 8, `post2 err=${e2m.toFixed(2)}m`);
});

